platform :ios, '17.0'
project 'AskInk.xcodeproj'
use_frameworks! :linkage => :static

target 'AskInk' do
  pod 'onnxruntime-objc', '~> 1.24.0'
  pod 'Yams', '~> 5.0'
  pod 'OpenCV', '~> 4.3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
    end
  end
end
